import os from 'node:os';
import path from 'node:path';

export const APP_NAME = 'wecom-cleaner';
export const PACKAGE_NAME = '@mison/wecom-cleaner';
export const APP_ASCII_LOGO = {
  wecom: [
    '██     ██ ███████  ██████   ██████  ███    ███',
    '██     ██ ██      ██      ██    ██ ████  ████',
    '██  █  ██ █████   ██      ██    ██ ██ ████ ██',
    '██ ███ ██ ██      ██      ██    ██ ██  ██  ██',
    ' ███ ███  ███████  ██████   ██████  ██      ██',
  ],
  cleaner: [
    ' ██████ ██      ███████  █████  ███    ██ ███████ ██████',
    '██      ██      ██      ██   ██ ████   ██ ██      ██   ██',
    '██      ██      █████   ███████ ██ ██  ██ █████   ██████',
    '██      ██      ██      ██   ██ ██  ██ ██ ██      ██   ██',
    ' ██████ ███████ ███████ ██   ██ ██   ████ ███████ ██   ██',
  ],
  subtitle: 'WeCom Cache Cleaner',
};

export const DEFAULT_PROFILE_ROOT = path.join(
  os.homedir(),
  'Library/Containers/com.tencent.WeWorkMac/Data/Documents/Profiles'
);

export const DEFAULT_STATE_ROOT = path.join(os.homedir(), '.wecom-cleaner-state');

export const MONTH_RE = /^(?<y>\d{4})-(?<m>\d{1,2})$/;

export const CACHE_CATEGORIES = [
  {
    key: 'images',
    label: '聊天图片',
    desc: '会话中的图片、截图等缓存。',
    relativePath: 'Caches/Images',
    defaultSelected: true,
  },
  {
    key: 'videos',
    label: '聊天视频',
    desc: '会话中的视频缓存。',
    relativePath: 'Caches/Videos',
    defaultSelected: true,
  },
  {
    key: 'files',
    label: '聊天文件',
    desc: '会话文件缓存（文档、压缩包等）。',
    relativePath: 'Caches/Files',
    defaultSelected: true,
  },
  {
    key: 'emotions',
    label: '表情资源',
    desc: '表情大图、表情资源缓存。',
    relativePath: 'Caches/Emotions',
    defaultSelected: true,
  },
  {
    key: 'emotion_thumbnails',
    label: '表情缩略图',
    desc: '表情预览图缓存。',
    relativePath: 'Caches/Emotion_Thumbnail',
    defaultSelected: true,
  },
  {
    key: 'video_thumbnails',
    label: '视频缩略图',
    desc: '视频封面和预览图缓存。',
    relativePath: 'Caches/Video_Thumbnail',
    defaultSelected: true,
  },
  {
    key: 'link_thumbnails',
    label: '链接缩略图',
    desc: '网页卡片预览图缓存。',
    relativePath: 'Caches/Link_Thumbnail',
    defaultSelected: true,
  },
  {
    key: 'voices',
    label: '语音消息',
    desc: '语音消息音频缓存。',
    relativePath: 'Caches/Voices',
    defaultSelected: true,
  },
  {
    key: 'wwsecurity',
    label: '受保护截图缓存',
    desc: 'wwsecurity 多层截图缓存。默认仅分析，清理需手动勾选。',
    relativePath: 'Caches/wwsecurity',
    defaultSelected: false,
  },
];

export const CATEGORY_MAP = new Map(CACHE_CATEGORIES.map((item) => [item.key, item]));

export const MODES = {
  START: 'start',
  CLEANUP_MONTHLY: 'cleanup_monthly',
  ANALYSIS_ONLY: 'analysis_only',
  SPACE_GOVERNANCE: 'space_governance',
  RESTORE: 'restore',
  DOCTOR: 'doctor',
  RECYCLE_MAINTAIN: 'recycle_maintain',
  CHECK_UPDATE: 'check_update',
  UPGRADE: 'upgrade',
  SYNC_SKILLS: 'sync_skills',
  SERVICE: 'service',
  SERVICE_INSTALL: 'service_install',
  SERVICE_UNINSTALL: 'service_uninstall',
  SERVICE_STATUS: 'service_status',
  SERVICE_RUN: 'service_run',
  SETTINGS: 'settings',
};

export const DELETE_MODES = {
  DIRECT: 'direct',
  RECYCLE: 'recycle',
  SERVICE_RECYCLE: 'service_recycle',
};

export const SPACE_GOVERNANCE_TIERS = {
  SAFE: 'safe',
  CAUTION: 'caution',
  PROTECTED: 'protected',
};

export const SPACE_GOVERNANCE_TIER_LABELS = new Map([
  [SPACE_GOVERNANCE_TIERS.SAFE, '安全层'],
  [SPACE_GOVERNANCE_TIERS.CAUTION, '谨慎层'],
  [SPACE_GOVERNANCE_TIERS.PROTECTED, '受保护层'],
]);

export const SPACE_GOVERNANCE_TARGETS = [
  {
    key: 'wxwork_temp_screencapture',
    label: '临时截图',
    desc: '企业微信截图临时目录，长期积累明显。',
    tier: SPACE_GOVERNANCE_TIERS.SAFE,
    scope: 'data_root',
    relativePath: 'Library/Application Support/WXWork/Temp/ScreenCapture',
  },
  {
    key: 'wxwork_temp_wetype_realpic',
    label: '临时图片输入缓存',
    desc: '输入法临时图片缓存。',
    tier: SPACE_GOVERNANCE_TIERS.SAFE,
    scope: 'data_root',
    relativePath: 'Library/Application Support/WXWork/Temp/wetype/realPic',
  },
  {
    key: 'wxwork_temp_ftn_local_cache',
    label: '文件传输临时缓存',
    desc: '文件传输临时目录。',
    tier: SPACE_GOVERNANCE_TIERS.SAFE,
    scope: 'data_root',
    relativePath: 'Library/Application Support/WXWork/Temp/FtnLocalCache',
  },
  {
    key: 'wxwork_temp_voip',
    label: '音视频临时目录',
    desc: '音视频临时缓存目录。',
    tier: SPACE_GOVERNANCE_TIERS.SAFE,
    scope: 'data_root',
    relativePath: 'Library/Application Support/WXWork/Temp/Voip',
  },
  {
    key: 'container_tmp',
    label: '容器临时目录(tmp)',
    desc: '应用容器临时目录，通常可安全清理。',
    tier: SPACE_GOVERNANCE_TIERS.SAFE,
    scope: 'data_root',
    relativePath: 'tmp',
  },
  {
    key: 'documents_log',
    label: '运行日志目录(log)',
    desc: '企业微信运行日志目录，清理后会按需重新生成。',
    tier: SPACE_GOVERNANCE_TIERS.SAFE,
    scope: 'data_root',
    relativePath: 'Documents/log',
  },
  {
    key: 'documents_gylog',
    label: 'GY日志目录',
    desc: '企业微信内部日志目录，通常可安全清理。',
    tier: SPACE_GOVERNANCE_TIERS.SAFE,
    scope: 'data_root',
    relativePath: 'Documents/GYLog',
  },
  {
    key: 'documents_gyosslog',
    label: 'GYOss日志目录',
    desc: '企业微信内部日志目录，通常可安全清理。',
    tier: SPACE_GOVERNANCE_TIERS.SAFE,
    scope: 'data_root',
    relativePath: 'Documents/GYOssLog',
  },
  {
    key: 'documents_user_avatar_url',
    label: '头像URL缓存',
    desc: '头像 URL 映射缓存，清理后会自动重建。',
    tier: SPACE_GOVERNANCE_TIERS.SAFE,
    scope: 'data_root',
    relativePath: 'Documents/UserAvatarUrl',
  },
  {
    key: 'documents_local_storage_index',
    label: '本地存储索引(local_storage_index.db)',
    desc: '企业微信本地存储索引数据库，不纳入自动删除范围。',
    tier: SPACE_GOVERNANCE_TIERS.PROTECTED,
    scope: 'data_root',
    relativePath: 'Documents/local_storage_index.db',
    deletable: false,
  },
  {
    key: 'profiles_secsdk_tmp',
    label: '安全SDK临时目录',
    desc: '账号目录下 SecSdk 临时文件。',
    tier: SPACE_GOVERNANCE_TIERS.SAFE,
    scope: 'profile',
    relativePath: 'SecSdk/tmp',
  },
  {
    key: 'profiles_sqlite_temp_dir',
    label: 'SQLite临时目录',
    desc: '账号目录下 sqlite_temp_dir 临时文件。',
    tier: SPACE_GOVERNANCE_TIERS.SAFE,
    scope: 'profile',
    relativePath: 'sqlite_temp_dir',
  },
  {
    key: 'profiles_publishsys_pkg',
    label: '文档组件缓存(Publishsys/pkg)',
    desc: '在线文档组件与脚本缓存，清理后首次打开会重新下载。',
    tier: SPACE_GOVERNANCE_TIERS.CAUTION,
    scope: 'profile',
    relativePath: 'Publishsys/pkg',
  },
  {
    key: 'profiles_voip',
    label: '账号音视频目录(VOIP)',
    desc: '账号目录下音视频缓存，清理后可能触发重新拉取。',
    tier: SPACE_GOVERNANCE_TIERS.CAUTION,
    scope: 'profile',
    relativePath: 'VOIP',
  },
  {
    key: 'wxwork_log',
    label: 'WXWork日志目录',
    desc: '应用日志目录，可清理但建议保留近期日志用于排障。',
    tier: SPACE_GOVERNANCE_TIERS.CAUTION,
    scope: 'data_root',
    relativePath: 'Library/Application Support/WXWork/Log',
  },
  {
    key: 'wxwork_voip_records',
    label: '音视频记录目录(VoipRecords)',
    desc: '企业微信音视频记录目录，清理前请确认不需要保留本地音视频记录。',
    tier: SPACE_GOVERNANCE_TIERS.CAUTION,
    scope: 'data_root',
    relativePath: 'Library/Application Support/WXWork/VoipRecords',
  },
  {
    key: 'crash_reporter',
    label: '崩溃报告目录(CrashReporter)',
    desc: '应用崩溃报告目录，可安全清理。',
    tier: SPACE_GOVERNANCE_TIERS.SAFE,
    scope: 'data_root',
    relativePath: 'Library/Application Support/CrashReporter',
  },
  {
    key: 'wxdrive_crash_dumps',
    label: '微盘崩溃转储',
    desc: 'WXDrive 崩溃转储目录，可安全清理。',
    tier: SPACE_GOVERNANCE_TIERS.SAFE,
    scope: 'data_root',
    relativePath: 'Library/Application Support/WXDrive/crashDumps',
  },
  {
    key: 'wxdrive_dist',
    label: '微盘组件缓存(dist)',
    desc: 'WXDrive 前端组件缓存，清理后通常会按需重建。',
    tier: SPACE_GOVERNANCE_TIERS.CAUTION,
    scope: 'data_root',
    relativePath: 'Library/Application Support/WXDrive/dist',
  },
  {
    key: 'wxdrive_sqlite',
    label: '微盘元数据(sqlite3)',
    desc: 'WXDrive 本地元数据数据库，不纳入自动删除范围。',
    tier: SPACE_GOVERNANCE_TIERS.PROTECTED,
    scope: 'data_root',
    relativePath: 'Library/Application Support/WXDrive/sqlite3',
    deletable: false,
  },
  {
    key: 'wxdrive_pref',
    label: '微盘偏好数据(wedrive_pref)',
    desc: 'WXDrive 偏好与状态数据，不纳入自动删除范围。',
    tier: SPACE_GOVERNANCE_TIERS.PROTECTED,
    scope: 'data_root',
    relativePath: 'Library/Application Support/WXDrive/wedrive_pref',
    deletable: false,
  },
  {
    key: 'wedoc_cache',
    label: '微文档缓存(Wedoc/cache)',
    desc: '微文档缓存目录，清理后通常会按需重建。',
    tier: SPACE_GOVERNANCE_TIERS.CAUTION,
    scope: 'data_root',
    relativePath: 'Library/Application Support/Wedoc/cache',
  },
  {
    key: 'wemail_cache',
    label: '邮箱缓存(WeMail/cache)',
    desc: '邮箱附件与渲染缓存，清理后可能触发重新拉取。',
    tier: SPACE_GOVERNANCE_TIERS.CAUTION,
    scope: 'data_root',
    relativePath: 'Library/Application Support/WeMail/cache',
  },
  {
    key: 'wemail_downloading',
    label: '邮箱下载临时目录',
    desc: 'WeMail 下载中的临时目录，建议确认当前无下载任务。',
    tier: SPACE_GOVERNANCE_TIERS.CAUTION,
    scope: 'data_root',
    relativePath: 'Library/Application Support/WeMail/downloading',
  },
  {
    key: 'wemail_patch',
    label: '邮箱补丁缓存',
    desc: 'WeMail 补丁缓存目录，清理后可重新生成。',
    tier: SPACE_GOVERNANCE_TIERS.CAUTION,
    scope: 'data_root',
    relativePath: 'Library/Application Support/WeMail/patch',
  },
  {
    key: 'wemail_heap_snapshot',
    label: '邮箱堆快照',
    desc: 'WeMail 调试堆快照目录，可安全清理。',
    tier: SPACE_GOVERNANCE_TIERS.SAFE,
    scope: 'data_root',
    relativePath: 'Library/Application Support/WeMail/heap_snapshort',
  },
  {
    key: 'wemail_sqlite',
    label: '邮箱元数据(sqlite)',
    desc: 'WeMail 本地元数据数据库，不纳入自动删除范围。',
    tier: SPACE_GOVERNANCE_TIERS.PROTECTED,
    scope: 'data_root',
    relativePath: 'Library/Application Support/WeMail/sqlite',
    deletable: false,
  },
  {
    key: 'wemail_local_draft',
    label: '邮箱本地草稿',
    desc: 'WeMail 本地草稿目录，不纳入自动删除范围。',
    tier: SPACE_GOVERNANCE_TIERS.PROTECTED,
    scope: 'data_root',
    relativePath: 'Library/Application Support/WeMail/local_draft',
    deletable: false,
  },
  {
    key: 'wemail_load_encrypted',
    label: '邮箱加密加载状态',
    desc: 'WeMail 加密加载状态文件，不纳入自动删除范围。',
    tier: SPACE_GOVERNANCE_TIERS.PROTECTED,
    scope: 'data_root',
    relativePath: 'Library/Application Support/WeMail/load_encrypted',
    deletable: false,
  },
  {
    key: 'wemail_mail_content',
    label: '邮箱正文缓存',
    desc: 'WeMail 邮件正文内容目录，不纳入自动删除范围。',
    tier: SPACE_GOVERNANCE_TIERS.PROTECTED,
    scope: 'data_root',
    relativePath: 'Library/Application Support/WeMail/mail_content',
    deletable: false,
  },
  {
    key: 'wemail_config',
    label: '邮箱配置(config)',
    desc: 'WeMail 配置目录，不纳入自动删除范围。',
    tier: SPACE_GOVERNANCE_TIERS.PROTECTED,
    scope: 'data_root',
    relativePath: 'Library/Application Support/WeMail/config',
    deletable: false,
  },
  {
    key: 'wemail_protocol',
    label: '邮箱协议数据(protocol)',
    desc: 'WeMail 协议状态目录，不纳入自动删除范围。',
    tier: SPACE_GOVERNANCE_TIERS.PROTECTED,
    scope: 'data_root',
    relativePath: 'Library/Application Support/WeMail/protocol',
    deletable: false,
  },
  {
    key: 'wedrive_temp',
    label: '微盘临时目录(.Temp)',
    desc: '微盘临时传输目录，清理前请确认无正在同步任务。',
    tier: SPACE_GOVERNANCE_TIERS.CAUTION,
    scope: 'data_root',
    relativePath: 'WeDrive/.Temp',
  },
  {
    key: 'wedrive_upload_temp',
    label: '微盘上传临时目录(.C2CUploadTemp)',
    desc: '微盘上传临时目录，清理前请确认无正在上传任务。',
    tier: SPACE_GOVERNANCE_TIERS.CAUTION,
    scope: 'data_root',
    relativePath: 'WeDrive/.C2CUploadTemp',
  },
  {
    key: 'wedrive_trash',
    label: '微盘回收目录(.WeDriveTrash-*)',
    desc: '微盘回收区目录，清理后不能在微盘回收区找回。',
    tier: SPACE_GOVERNANCE_TIERS.CAUTION,
    scope: 'data_root',
    relativePath: 'WeDrive/.WeDriveTrash-*',
  },
  {
    key: 'documents_cefcache',
    label: '内置网页缓存',
    desc: 'Web 内核缓存目录，清理后可能短时触发重新加载。',
    tier: SPACE_GOVERNANCE_TIERS.CAUTION,
    scope: 'data_root',
    relativePath: 'Documents/cefcache',
  },
  {
    key: 'documents_network',
    label: '网络缓存元数据(Network)',
    desc: '网络缓存元数据目录，清理后通常会重新建立。',
    tier: SPACE_GOVERNANCE_TIERS.CAUTION,
    scope: 'data_root',
    relativePath: 'Documents/Network',
  },
  {
    key: 'documents_local_en',
    label: '本地语言资源(local_en)',
    desc: '本地语言与资源目录，不纳入自动删除范围。',
    tier: SPACE_GOVERNANCE_TIERS.PROTECTED,
    scope: 'data_root',
    relativePath: 'Documents/local_en',
    deletable: false,
  },
  {
    key: 'documents_voip_nn_model',
    label: '音视频模型缓存(VoipNNModel)',
    desc: '音视频模型缓存目录，清理后通常会按需重新下载。',
    tier: SPACE_GOVERNANCE_TIERS.CAUTION,
    scope: 'data_root',
    relativePath: 'Documents/VoipNNModel',
  },
  {
    key: 'cef_user_data',
    label: 'CEF浏览器用户数据',
    desc: '内置浏览器用户态数据目录，仅建议分析，不纳入自动删除范围。',
    tier: SPACE_GOVERNANCE_TIERS.PROTECTED,
    scope: 'data_root',
    relativePath: 'Library/Application Support/CEF/User Data',
    deletable: false,
  },
  {
    key: 'appsupport_weworkmac',
    label: '应用支持数据(com.tencent.WeWorkMac)',
    desc: '企业微信应用支持目录，不纳入自动删除范围。',
    tier: SPACE_GOVERNANCE_TIERS.PROTECTED,
    scope: 'data_root',
    relativePath: 'Library/Application Support/com.tencent.WeWorkMac',
    deletable: false,
  },
  {
    key: 'appsupport_tencent',
    label: '应用支持数据(Tencent)',
    desc: 'Tencent 共享支持目录，不纳入自动删除范围。',
    tier: SPACE_GOVERNANCE_TIERS.PROTECTED,
    scope: 'data_root',
    relativePath: 'Library/Application Support/Tencent',
    deletable: false,
  },
  {
    key: 'appsupport_google',
    label: '应用支持数据(Google)',
    desc: '浏览器基础依赖目录，不纳入自动删除范围。',
    tier: SPACE_GOVERNANCE_TIERS.PROTECTED,
    scope: 'data_root',
    relativePath: 'Library/Application Support/Google',
    deletable: false,
  },
  {
    key: 'appsupport_liteav',
    label: '音视频组件数据(com.tencent.cloud.liteav)',
    desc: '音视频组件支持目录，不纳入自动删除范围。',
    tier: SPACE_GOVERNANCE_TIERS.PROTECTED,
    scope: 'data_root',
    relativePath: 'Library/Application Support/com.tencent.cloud.liteav',
    deletable: false,
  },
  {
    key: 'webkit_website_data_store',
    label: 'WebsiteDataStore 缓存',
    desc: 'WebKit 网站数据缓存，清理后会重新建立。',
    tier: SPACE_GOVERNANCE_TIERS.CAUTION,
    scope: 'data_root',
    relativePath: 'Library/WebKit/WebsiteDataStore',
  },
  {
    key: 'webkit_website_data',
    label: 'WebsiteData 缓存',
    desc: 'WebKit 额外站点数据缓存，清理后会重新建立。',
    tier: SPACE_GOVERNANCE_TIERS.CAUTION,
    scope: 'data_root',
    relativePath: 'Library/WebKit/WebsiteData',
  },
  {
    key: 'library_http_storages',
    label: 'HTTPStorages 缓存',
    desc: '系统 HTTP 存储缓存目录，清理后可能触发重新鉴权或重建缓存。',
    tier: SPACE_GOVERNANCE_TIERS.CAUTION,
    scope: 'data_root',
    relativePath: 'Library/HTTPStorages',
  },
  {
    key: 'library_preferences',
    label: '偏好设置(Preferences)',
    desc: '应用偏好设置目录，不纳入自动删除范围。',
    tier: SPACE_GOVERNANCE_TIERS.PROTECTED,
    scope: 'data_root',
    relativePath: 'Library/Preferences',
    deletable: false,
  },
  {
    key: 'library_cookies',
    label: 'Cookies 数据',
    desc: '会话与 Cookie 目录，不纳入自动删除范围。',
    tier: SPACE_GOVERNANCE_TIERS.PROTECTED,
    scope: 'data_root',
    relativePath: 'Library/Cookies',
    deletable: false,
  },
  {
    key: 'library_wecom_private',
    label: '私有组件数据(WecomPrivate)',
    desc: '企业微信私有组件目录，不纳入自动删除范围。',
    tier: SPACE_GOVERNANCE_TIERS.PROTECTED,
    scope: 'data_root',
    relativePath: 'Library/WecomPrivate',
    deletable: false,
  },
  {
    key: 'library_wecom_flutter_private',
    label: 'Flutter 私有组件数据',
    desc: '企业微信 Flutter 私有组件目录，不纳入自动删除范围。',
    tier: SPACE_GOVERNANCE_TIERS.PROTECTED,
    scope: 'data_root',
    relativePath: 'Library/WecomFlutterPrivate',
    deletable: false,
  },
  {
    key: 'library_caches',
    label: '容器通用缓存',
    desc: '应用容器下系统级缓存目录。',
    tier: SPACE_GOVERNANCE_TIERS.CAUTION,
    scope: 'data_root',
    relativePath: 'Library/Caches',
  },
  {
    key: 'profiles_wwsecurity',
    label: '受保护截图缓存(wwsecurity)',
    desc: 'Profiles 下多层截图缓存目录。',
    tier: SPACE_GOVERNANCE_TIERS.CAUTION,
    scope: 'profile',
    relativePath: 'Caches/wwsecurity',
  },
  {
    key: 'wxwork_data_core',
    label: '核心业务数据目录',
    desc: '核心数据区，仅支持分析，不允许删除。',
    tier: SPACE_GOVERNANCE_TIERS.PROTECTED,
    scope: 'data_root',
    relativePath: 'Library/Application Support/WXWork/Data',
    deletable: false,
  },
];

export const USER_LABEL_STOPWORDS = new Set(['真实姓名', '企业介绍', '我的业务', '新学期准备', '帮助企业']);

export const CORP_LABEL_STOPWORDS = new Set(['新学期准备', '腾讯科技股份有限公司', '其他']);

export const CJK_TEXT_RE = /[\u4e00-\u9fff]{2,24}/g;
export const EMAIL_RE = /[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}/g;
